### ISSUE TITLE
Can't commit after generating with bootstrap

### ISSUE THREAD

**Issue by erizocosmico** [bblfsh/sdk#1]
Hook prevents the first time your want to commit README.md after generating it with bootstrap.

**Comment by dpordomingo** [comment]
@erizocosmico maybe @mcuadros can confirm it, but I fixed that problem just running `bblfsh-sdk bootstrap`, and then add to the staging area the just changed files.

What I realized that happened, is that you are trying to commit something without including in the commit the README.md that is *outdated* compared with your current bblfsh SDK.

**Comment by erizocosmico** [comment]
Since this seems to not be an issue, closing for now. Will reopen if we come across this issue again.
