### ISSUE TITLE
Roles numeric values do not match in Go and Proto

### ISSUE THREAD

**Issue by smola** [bblfsh/sdk#126]
Roles numeric values do not match in Go and Proto. It seems they start at index 1 in Go and they start at index 0 in Proto.

It *might* be caused by a proteus issue: https://github.com/src-d/proteus/issues/86
(or it might not)

Once we fix this, we need to build new versions of published drivers.

**Comment by smola** [comment]
There's a workaround for the proteus stuff: https://github.com/src-d/proteus/issues/86#issuecomment-308339286

**Comment by vmarkovtsev** [comment]
Anyone? Although there is definitely a working workaround, this one is very nasty.

**Comment by juanjux** [comment]
@vmarkovtsev just merged this:

https://github.com/bblfsh/sdk/pull/139

**Comment by abeaumont** [comment]
As noted in #139, autogenererated file update is pending.
I still cannot assign to @mcarmonaa, so I'll do the PR with the autogenerated files myself.

**Comment by abeaumont** [comment]
Solved with #142. This should be fixed now and drivers should be updated.
