### ISSUE TITLE
support nested keys in ObjectToNoder

### ISSUE THREAD

**Issue by erizocosmico** [bblfsh/sdk#182]
Take as an example the AST generated by babylon:

```json
{
  "type": "SomeType",
  "loc": {
    "start": { "column": 1, "line": 1 },
    "end": { "column": 2, "line": 4 },
  },
  "offset": 1,
  "endOffset": 34
}
```

It'd be nice to be able to put as `LineKey` and so on `loc.start.line` instead of having to transform the AST.

**Comment by mcuadros** [comment]
This can be done with:
https://github.com/mcuadros/go-lookup
