### ISSUE TITLE
Expose the listing drivers endpoint for clients

### ISSUE THREAD

**Issue by dpordomingo** [bblfsh/sdk#253]
As required by https://github.com/bblfsh/client-scala/issues/68 and https://github.com/bblfsh/dashboard/issues/89, it would be needed to let the clients to fetch the list of installed drivers.

That API is part of the [bblfshd/daemon/protocol](https://github.com/bblfsh/bblfshd/blob/master/daemon/protocol/service.go#L15), and it's currently only [exported throwgh a unix socket for admin purposes](https://github.com/bblfsh/bblfshd/blob/master/cli/bblfshd/main.go#L51) so it can not be reached from the current clients.

Is there any plan to move the diver listing methods to the user network?

Here is the list of clients needing this:
- [ ] https://github.com/bblfsh/client-scala/issues/68 
- [ ] https://github.com/bblfsh/client-go/issues/53
- [ ] https://github.com/bblfsh/client-python/issues/98

**Comment by juanjux** [comment]
Yes, Soon™

(Soon = as soon as we finish with the SDK and drivers migration).
--

**Comment by dpordomingo** [comment]
As suggested by @bzz I added to the issue desc, a list of clients needing this.
(there is no issue yet in [client-python](https://github.com/bblfsh/client-python/issues))

**Comment by zurk** [comment]
Now we have it for python client also https://github.com/bblfsh/python-driver/issues/155

**Comment by dennwc** [comment]
@juanjux I can implement it. Don't want to block Apps because of this trivial feature.

**Comment by juanjux** [comment]
@dennwc Talk with David, he was interested in doing it too.

**Comment by bzz** [comment]
@dennwc 
>  Don't want to block Apps because of this trivial feature.

You are not - we actually have already something working for now, only for our case.

At the same time - we do not want to steal you precious time from more complex work and would be happy to contribute this one, under your careful review and supervision of course!

If that would be fine with you guys, @juanjux @dennwc  - AFAIK indeed @dpordomingo will be happy to start looking into that asap.

**Comment by zurk** [comment]
@dpordomingo can you add https://github.com/bblfsh/client-python/issues/98 also in your list in first message please?

**Comment by dpordomingo** [comment]
Added python to the desc.
I'd like to take a look at it this weekend and I'll ask you next week to confirm I understood how to do it (I never worked with bblfsh, so lets see if I can help :wink:

**Comment by juanjux** [comment]
Excellent @dorpordomingo, btw we're hiring! 😁

**Comment by dpordomingo** [comment]
I'll start looking into this today. Let's see if I find the way to do it :dagger:

**Comment by bzz** [comment]
I belive this has been done now, and included in https://github.com/bblfsh/bblfshd/releases/tag/v2.5.0

@juanjux shall we close this now, as all subsequent work would be tracked under the issues in appropriate `client-*` repos?
