### ISSUE TITLE
Node.Hash is always zero

### ISSUE THREAD

**Issue by smola** [bblfsh/sdk#290]
From @ajnavarro yesterday ([more](https://github.com/ajnavarro/dupes/blob/master/empathy-log.md)):

> * Using node.Hash() method, that after 20 min testing is always returning 0
>    * _methods that are not implemented should panic or return an error_

Is this function currently used? Maybe we should just remove it until it is?

**Comment by dennwc** [comment]
I removed it as soon as I started v2 branch. So it's already fixed in master.
