### ISSUE TITLE
bblfsh-sdk does not account for the driver's SDK version

### ISSUE THREAD

**Issue by dennwc** [bblfsh/sdk#325]
Currently, if the version of the driver and `bblfsh-sdk` tool doesn't match, the tool will always try to override "changed" files. This change will break the driver's CI since it will install an older SDK version, as required by the manifest.

Instead, the tool should get the requested SDK version in the manifest (we have this functionality already) and compare it with it's own version. The tool should fail with a meaningful message if major+minor versions are not the same.

An alternative is to automatically execute `go run ./vendor/gopkg.in/bblfsh/sdk.v2/cmd/bblfsh-sdk/main.go` when running the tool if it exists in the `vendor` directory.

CC @juanjux

**Comment by bzz** [comment]
I like the idea of not able to make a mistake by running vendored version of the bblfsh-sdk binary.

**Comment by bzz** [comment]
I guess this is related to #326

**Comment by creachadair** [comment]
If the two need to be in sync, should we include a handshake in the protocol so that the library and the SDK can tell whether they have compatible versions?

I'm probably missing something, but is there some reason why these aren't released together if they depend on each other? Or are they, and this is only affecting the CI?

**Comment by dennwc** [comment]
@bzz I don't think `-v` will help here since it cannot detect it's own minor version. And it's not required - you just need to run a copy from `vendor` if it exists. For development, you can either remove it from `vendor`, or bump version with dep.

@creachadair The problem is that we have a `bblfsh-sdk` tool installed globally, and each driver also has a `vendor` with a potentially different version. Sometimes when we backport changes, it may try to update the driver to a "future" version (or vise-versa).

It's only relevant to driver developers when testing and updating drivers, so there is no protocol here - you simply run a tool that may overwrite some files in the driver according to requirements of a specific SDK version. And the proposal is to detect the `vendor` and automatically execute `bblfsh-sdk` tool from it, so even when you have a tool installed globally, it will still do the right thing.

**Comment by dennwc** [comment]
It's not that hard to stat `vendor` and `exec("go run ./vendor/.../bblfsh-sdk")`. But printing a warning definitely makes sense.

If the solution to an error is clear, the tool may do it automatically.
