### ISSUE TITLE
Automate the driver's SDK version upgrade

### ISSUE THREAD

**Issue by dennwc** [bblfsh/sdk#326]
Currently updating the SDK version is time-consuming and error-prone. 

The process of upgrading a single driver is trivial but a bit long (assuming latest `bblfsh-sdk` tool installed):
1) Clone/pull the latest driver version.
2) Change the version in the `Gopkg.toml` from `vA.B.x` to `vA.C.x`.
3) Run `dep ensure --update gopkg.in/bblfsh/sdk.v2`. In rare cases, it's necessary to run `dep ensure`.
4) Run `bblfsh-sdk update`.
5) Execute a custom script that might change driver files in a predictable way (independent of the language).
6) Run `bblfsh-sdk test`, if it fails - cancel the process.
7) Commit and open a PR, wait for CI to complete.
8) Tag a release with the specified commit message. The tool should automatically bump either minor or patch version, as requested.

This process needs to be repeated manually for 10+ drivers without any changes.

I propose to automate this process.

First, we can implement it as a part of `bblfsh-sdk` tool to run locally. I have a simple prototype that does this, but it might need to be updated.

Later we can add it as a webhook using Cloud Functions or whatever works best (and supports Go).

CC @smola @juanjux @bzz

**Comment by juanjux** [comment]
Totally agree. Automating tedious and error prone processes have my 👍

**Comment by smola** [comment]
:+1: it makes sense to script this thing, at least for running locally.

If we automate with a webhook, how would we determine if we should bump major, minor or patch? Based on SDK version change?

**Comment by bzz** [comment]
For simple SDK version update, one can use
```bash
#!/usr/bin/env bash

set -e
set -x

sed -i 's/v2.6.x/v2.8.x/' ./Gopkg.toml
dep ensure --update gopkg.in/bblfsh/sdk.v2
go run ./vendor/gopkg.in/bblfsh/sdk.v2/cmd/bblfsh-sdk/main.go update
go run ./vendor/gopkg.in/bblfsh/sdk.v2/cmd/bblfsh-sdk/main.go test

git checkout -b sdk/version-bump
git add Gopkg.*
git commit -s -S -m "sdk: bump version to latest v2.8.x"
git push origin sdk/version-bump
```

**Comment by smola** [comment]
> git add Gopkg.*

Does `update` never update other files?

**Comment by bzz** [comment]
>> git add Gopkg.*
>
>Does update never update other files?

In this case, update did not change anything and this script is only handling a simplest case at hand, adding to git only results of `dep ensure`.

But in general case AFAIK `update` can at least change any of the [managed files](https://github.com/bblfsh/sdk/blob/master/cmd/bblfsh-sdk/cmd/update.go#L29) - which of course should be handled by a general automation.

**Comment by bzz** [comment]
Below RFC for simplest useful automation, after a first hand experience of managing SDK update for drivers in https://github.com/bblfsh/client-go/issues/102

## Proposal

I would suggest having 3 small CLI scripts for this automation, that communication though STDIO:

  1. Bump versions, commit, push (1-6) 
    - Input: new SDK version number
    - Output: URLs for PR creation from new branches in driver repos
      This would be almost a trivial change from the script above.
  2. Create PRs
    - Input: links for PR creation, title, description
    - Output: links to new PRs 
  3. Cut releases (8)
    - Input: list of repositories
    - Output: new releases from HEAD
      This one can eventually made to be "smarter": consume an output of the previous step - a list of open PRs; check if PRs are approved by any of the Maintainers  + CI passes; and only then merge + cut releases from those SHAs.

Motivation for such separation: 
 - each tool will be super-simple (no magic)
 - event if 3 is super dumb and PRs are merged manually between 2 and 3, this would already simplify boring bits of the release process
 - manual intervention is till possible between each step if desired, as well as full automation though pipes
 - unix way

**Comment by creachadair** [comment]
Re: RFC. I like this approach. 

I've had good luck using freestanding (meaning `go run`-able) Go programs for scripting tasks like this.

**Comment by bzz** [comment]
> Re: RFC. I like this approach.

👍 

> I've had good luck using freestanding (meaning `go run`-able) Go programs for scripting tasks like this.

I have a mixed feelings about that - do whatever you want to me, but I would prefer any time

```bash
set -e
if [[ -f "Gopkg.lock" ]]; then
  dep ensure
fi
if [[ ! -d "vendor" ]]; then
  dep ensure
fi
```
to 
```golang
	if _, err := os.Stat(d.path("Gopkg.toml")); os.IsNotExist(err) {
		err = execIn(d.root, nil, "dep", "init")
		if err != nil {
			return err
		}
	} else if err != nil {
		return err
	}
	if _, err := os.Stat(d.path("Gopkg.lock")); os.IsNotExist(err) {
		err = execIn(d.root, nil, "dep", "ensure")
		if err != nil {
			return err
		}
	} else if err != nil {
		return err
	}
	if _, err := os.Stat(d.path("vendor")); os.IsNotExist(err) {
		err = execIn(d.root, nil, "dep", "ensure", "--vendor-only")
		if err != nil {
			return err
		}
	} else if err != nil {
		return err
	}
```
([source](https://github.com/bblfsh/sdk/blob/master/build/golang.go))

**Comment by dennwc** [comment]
@bzz Can be one-line helper though. With Go it's easier to manipulate IO streams and processes, especially for driver tests.

**Comment by bzz** [comment]
> With Go it's easier to manipulate IO streams and processes, especially for driver tests.

for sure, Go is better if complexity of the task is such that it requires arrays or IO stream manipulation beyond `grep`. That is why I advocate shell applicability only for complexity level of the example above. 

For me, ideal design would include simple things that are easy to bootstrap done using shell scripts and then replace with Golang-built binaries with the same names, as complexity grows.

**Comment by creachadair** [comment]
> For me, ideal design would include simple things that are easy to bootstrap done using shell scripts and then replace with Golang-built binaries with the same names, as complexity grows.

I agree. However, I think we have to be careful. The pattern I have observed in general is that the tool starts life as a simple shell script, and then grows incrementally until it becomes a tangle of fussy redirections and `sed` hacks and leans on corner cases that don't work the same way from one shell to another. And by the time that happens, the expense of replacing it with a better language is much higher.

You're right, I think, that investing in a better language up front (whether that's Go or Python or Ruby or whatever) is more work initially: But I also think it grows with more grace as the environment expands. Moreover, it is a lot easier to do programmatic transformations on almost any other language, to fix bugs, add tests, and so on. When a script is small it probably doesn't need tests, but the more work it does, the more I think it should behave like real software rather than simply a command-list.

That said: I think the most important aspect of this issue is to get some automation in place, and with care I think we _can_ start out simple and grow. I just wanted to make that point early in the process so that we are intentional about the gradient.

**Comment by lwsanty** [comment]
Let me propose one more solution:
1) SDK repo should have some list with supported drivers
2) SDK repo should have a git hook on release event
3) on hook event Jenkins or Travis build to be started:
    _for each driver in the list:_ 
  a) pull repo's master branch
  b) create a new branch `update-sdk-vx_x_x`
  c) `go get -u github.com/bblfsh/sdk/v3 && go run ./update.go && go mod tidy`
  d) commit and create pull request

These pull requests should be checked manually in any case...
_Unresolved problem here:_ build `bblfsh` container with `latest-drivers` tag

@dennwc @bzz @creachadair @smola 
I could probably miss something here so please tell me wdyt?

Just in case this approach is accepted it's instantly blocked with https://github.com/src-d/infrastructure/issues/992

**Comment by dennwc** [comment]
@lwsanty Sounds good to me!

But it will be also nice to be able to run this process manually, adding a custom script to execute for each driver. It may be the Go version bump, for example, as we encountered today.

Checking PRs manually sounds OK for now. Even having a process that submits those 10+ PRs automatically would be a huge improvement.

**Comment by lwsanty** [comment]
@dennwc  you are right,
I think that we can neglect the webhook for the first time because
1) Jenkins is not accessible from github
2) I think it's ok to trigger manually the process "update all repos", 'cause new SDK versions are not been released a couple of times per day...

So eventually we can:
1) create utility inside sdk repo that can perform such operations as update repos and create pr's
2) we can run this utility either locally or by [triggering Jenkins via URL](https://humanwhocodes.com/blog/2015/10/triggering-jenkins-builds-by-url/)

**Comment by dennwc** [comment]
By the way, maybe we can actually use a webhook for this. But instead of exposing it to the Web, we can expose it to the cluster only, and then make a tool that triggers it (assuming local `sshuttle` connection).

Since SDK is not released that often, it will be okay to trigger the update manually using this mechanism.

**Comment by lwsanty** [comment]
@dennwc that's exactly what I meant in `2. we can run this utility either locally or by triggering Jenkins via URL` :)

**Comment by lwsanty** [comment]
Here's the link to discussion of my proposal
https://github.com/src-d/minutes/pull/671/files

I consider these minutes as a green light to start working on this task.

**Comment by creachadair** [comment]
> Here's the link to discussion of my proposal
> https://github.com/src-d/minutes/pull/671/files
> 
> I consider these minutes as a green light to start working on this task.

Yes, I agree.

**Comment by lwsanty** [comment]
this issue also requires Jenkinsfile https://github.com/src-d/infrastructure/issues/992
