### ISSUE TITLE
SDK 2.13 fails to generate specific semantic fixture that worked with 2.12

### ISSUE THREAD

**Issue by juanjux** [bblfsh/sdk#353]
## Summary

Trying to generate fixtures for the Python driver after upgrading to 2.13.x I noticed that generation of semantic fixtures (using `bblfsh-sdk test`) stopped after this file:

https://github.com/bblfsh/python-driver/blob/master/fixtures/issue_server101.py

Neither that file or any other that came after it (in alphabetic order) had the `.py.sem.uast` files generated. There wasn't any error.

## Repro

```bash
cd $GOPATH/src/github.com/bblfsh
git clone https://github.com/bblfsh/python-driver.git
# Edit Gopkg.toml, replace 2.12.x for 2.13.x in SDK
bblfsh-sdk test
ls fixtures/*.sem.uast # notice how they stop at issue97_lessThan.py.sem.uast
```

## Expected

All the semantic fixtures are generated OR an error is produced.

## Observed

No errors and no files generated after `issue97_lessThan.py.sem.uast`.

**Comment by dennwc** [comment]
Will check it.

**Comment by dennwc** [comment]
Note that steps should include:
```
dep ensure --update gopkg.in/bblfsh/sdk.v2
```
after changing the `toml`

**Comment by juanjux** [comment]
Nope, problem is elsewhere, could make 2.13 work and 2.12 fail changing one of the driver annotations, closing.
