### ISSUE TITLE
Function arguments sorted in the wrong order

### ISSUE THREAD

**Issue by juanjux** [bblfsh/sdk#39]
Doing the integration tests for the Python driver I noticed that the function arguments list, whose items has the internalRole "args" and Role MethodInvocationArguments (childrens of a MethodInvocation) are not sorting in the right order.

For this code:

```python
print("something1", 42, somesymbbol)
```
I will attach the complete jsons for the Python AST and the generated UAST to this issue

[unsorted_args_jsons.zip](https://github.com/bblfsh/sdk/files/872445/unsorted_args_jsons.zip)

 but to see it clearly a (simplified) version of the Python AST part of the arguments is:
 
```json
                  "args" : [
                     {
                        "LiteralValue" : "something1",
                        "ast_type" : "StringLiteral"
                     },
                     {
                        "ast_type" : "NumLiteral",
                        "NumType" : "int",
                        "LiteralValue" : 42,
                     },
                     {
                        "id" : "somesymbbol",
                        "ast_type" : "Name"
                     }
                  ],
```

While the (simplified) UAST generated is:

```json
                     {
                        "Properties" : {
                           "NumType" : "0",
                           "internalRole" : "args"
                        },
                        "Roles" : [ 59, 54 ],
                        "Token" : "42",
                        "InternalType" : "NumLiteral"
                     },
                     {
                        "InternalType" : "Name",
                        "Token" : "somesymbbol",
                        "Roles" : [ 54, 0 ],
                        "Properties" : {
                           "internalRole" : "args",
                        },
                     },
                     {
                        "InternalType" : "StringLiteral",
                        "Properties" : {
                           "internalRole" : "args"
                        },
                        "Roles" : [ 58, 54 ],
                        "Token" : "something1",
                     }
```

As you can see, the arguments are not in the same order for the UAST. The Rule I'm using for them is:

```go
		On(HasInternalType(pyast.Call)).Roles(MethodInvocation).Children(
			On(HasInternalRole("args")).Roles(MethodInvocationArgument),
			On(HasInternalRole("func")).Self(On(HasInternalRole("id"))).Roles(MethodInvocationName),
			On(HasInternalRole("func")).Self(On(HasInternalRole("attr"))).Roles(MethodInvocationName),
			On(HasInternalRole("func")).Self(On(HasInternalType(pyast.Attribute))).Children(
				On(HasInternalRole("id")).Roles(MethodInvocationObject),
			),
		),
```

**Comment by smola** [comment]
@juanjux We sort children by its offset in the file, but it seems that the Python driver does not provide offsets for literals or function arguments? If the AST parser does not preserve offsets (or line/col) we can make BaseToNoder preserve order as it is found in the incoming JSON.

**Comment by juanjux** [comment]
It was a problem with the Python AST not adding the positional properties, once that was fixed the order is right.

**Comment by juanjux** [comment]
@smola it does provide line and col but I do a little massaging of the output of literal strings and the bug was there. But keeping the order of json list elements would be desirable.
