### ISSUE TITLE
Some children are randomly sorted on the pretty print

### ISSUE THREAD

**Issue by juanjux** [bblfsh/sdk#76]
*(I'll take a look at this, adding the issue to add a note on the sprint task for prefix/infix/postfix that depends on this being fixed).*

How to reproduce:

- On a driver with integration tests (for example Python or Java), delete tests/*.uast and tests/*.native.
- `make integration-test` so these files are regenerated again.
- `git commit` adding the new files.
- Repeat the steps (delete, regenerate) without making any other changes.
- `git diff` 

[Example commit created just for debugging this.](https://github.com/juanjux/python-driver/commit/7eed4d54febb48d4f9c7537ec085c479120b1789)

**Comment by smola** [comment]
Pretty printing does not alter children order, so it must be a problem in BaseToNoder not being deterministic for some case.

**Comment by juanjux** [comment]
Mmmm, this was closed and in fact if this didn't work integration tests wouldn't pass, click slip? Preventively closing it again.
