### ISSUE TITLE
Running container fails on GOPATH \w multiple dirs entries

### ISSUE THREAD

**Issue by bzz** [bblfsh/sdk#84]
Default GOPATH on GCE cloud console is `"/home/alex/gopath:/google/gopath"`

But running a build docker container for any driver fails on [mounting such GOPATH](https://github.com/bblfsh/sdk/blob/master/etc/build/make/rules.mk#L43)

```
+ docker run --rm -t -u bblfsh:1000 -v /home/alex/java-driver:/opt/driver/src/ -v /home/alex/gopath:/google/gopath:/go -e ENVIRONMENT=bblfs
h/java-driver-build-with-go bblfsh/java-driver-build-with-go make test-driver-internal

docker: Error response from daemon: Invalid bind mount spec "/home/alex/gopath:/google/gopath:/go": invalid mode: /go.
See 'docker run --help'.
```

**Comment by bzz** [comment]
This also breaks the driver builds i.e in case of python

```
docker: Error response from daemon: Invalid bind mount spec "/home/alex/gopath:/google/gopath:/go": invalid mode: /go.
See 'docker run --help'.
/home/alex/gopath/src/github.com/bblfsh/python-driver/.sdk/make/rules.mk:101: recipe for target 'build-driver' failed
make: *** [build-driver] Error 125
```

**Comment by abeaumont** [comment]
According to https://github.com/golang/go/wiki/GOPATH, it may effectively be a list of paths even if usually not needed, so marking this as a bug.

**Comment by abeaumont** [comment]
The obvious solution is to parse GOPATH and just extract one of the paths in case there's more than one. The question is which one to extract, since it seems rather arbitrary. Maybe we should just use the first one and document it.

Any better ideas?

**Comment by juanjux** [comment]
@bzz does it work in that environment if you use a single GOPATH?
