### ISSUE TITLE
Bootstraping a driver

### ISSUE THREAD

**Issue by dpordomingo** [bblfsh/sdk#9]
Some things that I found missing (it could be maybe a lack of documentation)

### Driver
Inside the driver, after running `bblfsh-sdk prepare-build`
- I think it should be autogenerated:
  - `native` directory if it does not exists,
  - `.gitignore` with a `.sdk` rule; if `.gitignore` exists without that rule, then append it.
- It should be great a hint in the root `Makefile` when running `make` if the SDK has not been yet installing, just saying something like:
_"It is needed to instal the bblfsh SDK before; it can be done with: `bblfsh-sdk prepare-build`"_
- It should be explained somewhere that to start working with a driver, it is needed to run, in order:
```
bblfsh-sdk prepare-build
bblfsh-sdk init
```

### SDK
Inside `bblfsh/sdk` project
- `make test` does not pass
```
> make test
--- FAIL: github.com/bblfsh/sdk/etc/skeleton/driver/normalizer :: TestNativeBinary
        Error Trace:    normalizer_test.go:18
	Error:		Expected nil, but got: &os.PathError{Op:"fork/exec", Path:"/opt/driver/src/build/native", Err:0x2}
```
- is it needed to run `make all` before doing anything? anyway tests keeps failing

**Comment by juanjux** [comment]
`make test` works now (it must be in `GOPATH`), the first point remains.

**Comment by juanjux** [comment]
PR #224 should fix the remaining items in your list, thanks!
