### ISSUE TITLE
The native version badge in the README.md mentions the driver name, instead of the native language

### ISSUE THREAD

**Issue by alcortesm** [bblfsh/sdk#92]
For instance, in case of the bash-driver, whose native driver is writen in Java, the batch should say `java version: 1.8....` but instead it says `bash version: 1.8....`.

**Comment by juanjux** [comment]
Mmmm, this is arguable, it's useful that the badge shows the language we're being parsing, if you want to know the implementation language you have the top bar on github that shows it.

**Comment by dennwc** [comment]
I don't think it's relevant and I agree with @juanjux on this. Closing.
